version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres_db_car
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdatacar:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=car_db
      - POSTGRES_USER=dwiki
      - POSTGRES_PASSWORD=dwiki123
volumes:
  pgdatacar:
