name: Rent Car Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: dwiki
          POSTGRES_PASSWORD: dwiki123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Create .env file
        run: |
          touch .env
          echo DATABASE_URL=postgresql://dwiki:dwiki123@127.0.0.1:5432/car_db >> .env
      - name: Migrate database
        run: npx knex migrate:latest && npx knex seed:run
      - name: Test Coverage
        run: npm run coverage
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
