name: Rent Car Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: dwiki
          POSTGRES_PASSWORD: dwiki123
          POSTGRES_DB: car_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Check Database with Query
        run: |
          sleep 10
          PGPASSWORD=dwiki123 psql -h localhost -U dwiki -d car_db -c "SELECT 1;"
      - name: Create .env file
        run: |
          touch .env
          echo DATABASE_URL=postgresql://dwiki:dwiki123@127.0.0.1:5432/car_db >> .env
      - name: Display .env file
        run: cat .env
      - name: Wait for Database
        run: sleep 10
      - name: migration list
        run: npx knex migrate:list
      - name: run migration
        run: npx knex migrate:latest
      - name: run seeding
        run: npx knex migrate:run
      - name: Test Coverage
        run: npm run coverage
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
